apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-loadbalancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohamediag/core-components
    targetRevision: HEAD
    path: aws-loadBalancer-controller/manifest
  destination:
    server: https://kubernetes.default.svc
    namespace: aws-load-balancer-controller