apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: argo-cd
  repo: oci://ghcr.io/argoproj/argo-helm
  version: 7.6.8
  releaseName: argocd
  apiVersions:
  - monitoring.coreos.com/v1
  valuesFile: values.yaml

