apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: aws-load-balancer-controller
  repo: https://aws.github.io/eks-charts
  version:  1.9.0
  releaseName: aws-load-balancer-controller
  valuesFile: values.yaml
  namespace: aws-load-balancer-controller

